# Generated by Django 5.2.8 on 2025-11-27 14:26

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "password",
                    models.CharField(max_length=128, verbose_name="password"),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="date joined",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="Tell others about yourself",
                        max_length=500,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Your city or region",
                        max_length=100,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Current latitude coordinate",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Current longitude coordinate",
                        max_digits=9,
                        null=True,
                    ),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        help_text="Upload a profile picture",
                        null=True,
                        upload_to="profile_pictures/",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "is_profile_public",
                    models.BooleanField(
                        default=True,
                        help_text="Make your profile visible to other users",
                    ),
                ),
                (
                    "allow_direct_messages",
                    models.BooleanField(
                        default=True,
                        help_text="Allow other users to send you direct messages",
                    ),
                ),
                ("reputation_score", models.IntegerField(default=0)),
                ("successful_trades", models.IntegerField(default=0)),
                ("has_initial_taste", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_active", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "accounts_user",
                "ordering": ["-created_at"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following_relationships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "following",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follower_relationships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Follow Relationship",
                "verbose_name_plural": "Follow Relationships",
                "db_table": "accounts_follow",
                "unique_together": {("follower", "following")},
            },
        ),
        migrations.AddField(
            model_name="user",
            name="followers",
            field=models.ManyToManyField(
                related_name="following",
                through="accounts.Follow",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_notifications", models.BooleanField(default=True)),
                ("push_notifications", models.BooleanField(default=True)),
                (
                    "barter_request_notifications",
                    models.BooleanField(default=True),
                ),
                ("message_notifications", models.BooleanField(default=True)),
                ("follow_notifications", models.BooleanField(default=True)),
                ("show_email", models.BooleanField(default=False)),
                ("show_phone", models.BooleanField(default=False)),
                ("show_location", models.BooleanField(default=True)),
                (
                    "max_barter_distance",
                    models.IntegerField(
                        default=50,
                        help_text="Maximum distance (in km) for book bartering",
                    ),
                ),
                (
                    "preferred_meeting_locations",
                    models.TextField(
                        blank=True,
                        help_text="Preferred locations for book exchanges",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Preferences",
                "verbose_name_plural": "User Preferences",
                "db_table": "accounts_user_preferences",
            },
        ),
        migrations.CreateModel(
            name="UserTaste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "favorite_genres",
                    models.JSONField(
                        default=list,
                        help_text="List of favorite book genres (keys)",
                    ),
                ),
                (
                    "favorite_authors",
                    models.JSONField(
                        default=list,
                        help_text="List of favorite authors (keys)",
                    ),
                ),
                (
                    "favorite_books",
                    models.JSONField(
                        default=list, help_text="List of favorite books (keys)"
                    ),
                ),
                (
                    "preferred_length",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SHORT", "짧음"),
                            ("MEDIUM", "보통"),
                            ("LONG", "두꺼움"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "preferred_moods",
                    models.JSONField(
                        default=list,
                        help_text="List of preferred book moods (keys)",
                    ),
                ),
                (
                    "reading_purposes",
                    models.JSONField(
                        default=list,
                        help_text="List of reading purposes (keys)",
                    ),
                ),
                (
                    "trade_place_name",
                    models.CharField(
                        blank=True,
                        help_text="Preferred trade place name (e.g., cafe, library)",
                        max_length=120,
                    ),
                ),
                (
                    "trade_address",
                    models.CharField(
                        blank=True,
                        help_text="Preferred trade address (optional)",
                        max_length=200,
                    ),
                ),
                (
                    "current_step",
                    models.IntegerField(
                        default=1,
                        help_text="Current categorization step (1-7)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taste",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Taste",
                "verbose_name_plural": "User Tastes",
            },
        ),
    ]
