# Generated by Django 5.2.7 on 2025-10-28 11:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_has_initial_taste_usertaste"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usertaste",
            options={
                "verbose_name": "User Taste",
                "verbose_name_plural": "User Tastes",
            },
        ),
        migrations.RemoveField(
            model_name="user",
            name="favorite_genres",
        ),
        migrations.RemoveField(
            model_name="usertaste",
            name="preferred_language",
        ),
        migrations.RemoveField(
            model_name="usertaste",
            name="reading_frequency",
        ),
        migrations.RemoveField(
            model_name="usertaste",
            name="reading_style",
        ),
        migrations.AddField(
            model_name="usertaste",
            name="current_step",
            field=models.IntegerField(
                default=1, help_text="Current categorization step (1-6)"
            ),
        ),
        migrations.AddField(
            model_name="usertaste",
            name="favorite_authors",
            field=models.JSONField(
                default=list, help_text="List of favorite authors (keys)"
            ),
        ),
        migrations.AddField(
            model_name="usertaste",
            name="favorite_books",
            field=models.JSONField(
                default=list, help_text="List of favorite books (keys)"
            ),
        ),
        migrations.AddField(
            model_name="usertaste",
            name="preferred_length",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SHORT", "짧음"),
                    ("MEDIUM", "보통"),
                    ("LONG", "두꺼움"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="usertaste",
            name="preferred_moods",
            field=models.JSONField(
                default=list, help_text="List of preferred book moods (keys)"
            ),
        ),
        migrations.AddField(
            model_name="usertaste",
            name="reading_purposes",
            field=models.JSONField(
                default=list, help_text="List of reading purposes (keys)"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="followers",
            field=models.ManyToManyField(
                related_name="following",
                through="accounts.Follow",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="usertaste",
            name="favorite_genres",
            field=models.JSONField(
                default=list, help_text="List of favorite book genres (keys)"
            ),
        ),
    ]
