# Generated by Django 5.2.7 on 2025-11-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_add_user_lat_lon"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertaste",
            name="trade_place_name",
            field=models.CharField(
                max_length=120,
                blank=True,
                help_text="Preferred trade place name (e.g., cafe, library)",
            ),
        ),
        migrations.AddField(
            model_name="usertaste",
            name="trade_address",
            field=models.CharField(
                max_length=200,
                blank=True,
                help_text="Preferred trade address (optional)",
            ),
        ),
        migrations.AddField(
            model_name="usertaste",
            name="trade_latitude",
            field=models.DecimalField(
                max_digits=9,
                decimal_places=6,
                null=True,
                blank=True,
                help_text="Preferred trade latitude coordinate",
            ),
        ),
        migrations.AddField(
            model_name="usertaste",
            name="trade_longitude",
            field=models.DecimalField(
                max_digits=9,
                decimal_places=6,
                null=True,
                blank=True,
                help_text="Preferred trade longitude coordinate",
            ),
        ),
        migrations.AlterField(
            model_name="usertaste",
            name="current_step",
            field=models.IntegerField(
                default=1, help_text="Current categorization step (1-7)"
            ),
        ),
    ]
