# Generated by Django 5.2.7 on 2025-11-11 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_add_trade_fields_to_usertaste"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="user",
            name="longitude",
        ),
        migrations.RemoveField(
            model_name="usertaste",
            name="trade_latitude",
        ),
        migrations.RemoveField(
            model_name="usertaste",
            name="trade_longitude",
        ),
    ]
