# Generated by Django 5.2.8 on 2025-11-27 14:26

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BarterRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        help_text="Rate the other user from 1 to 5 stars",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "communication_rating",
                    models.IntegerField(
                        help_text="How well did they communicate?",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "punctuality_rating",
                    models.IntegerField(
                        help_text="Were they on time for the meeting?",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "book_condition_rating",
                    models.IntegerField(
                        help_text="Was the book condition as described?",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "feedback",
                    models.TextField(
                        blank=True,
                        help_text="Optional feedback about the barter experience",
                    ),
                ),
                ("would_barter_again", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Barter Rating",
                "verbose_name_plural": "Barter Ratings",
                "db_table": "barter_barter_rating",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BarterRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "offered_book_ids",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of 3 book IDs proposed by requester",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Message from requester explaining the barter request"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("counter_proposed", "Counter Proposed"),
                            ("rejected", "Rejected"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "preferred_meeting_type",
                    models.CharField(
                        choices=[
                            ("in_person", "In Person"),
                            ("mail", "Mail Exchange"),
                            ("pickup", "Pickup/Dropoff"),
                        ],
                        default="in_person",
                        max_length=20,
                    ),
                ),
                (
                    "proposed_meeting_location",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "proposed_meeting_time",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("response_message", models.TextField(blank=True)),
                ("response_date", models.DateTimeField(blank=True, null=True)),
                (
                    "completed_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("completion_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this barter request expires",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Barter Request",
                "verbose_name_plural": "Barter Requests",
                "db_table": "barter_barter_request",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BarterTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("disputed", "Disputed"),
                        ],
                        default="in_progress",
                        max_length=20,
                    ),
                ),
                (
                    "actual_meeting_location",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "actual_meeting_time",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "meeting_type",
                    models.CharField(
                        choices=[
                            ("in_person", "In Person"),
                            ("mail", "Mail Exchange"),
                            ("pickup", "Pickup/Dropoff"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "completed_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "completion_confirmed_by_requester",
                    models.BooleanField(default=False),
                ),
                (
                    "completion_confirmed_by_recipient",
                    models.BooleanField(default=False),
                ),
                ("transaction_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Barter Transaction",
                "verbose_name_plural": "Barter Transactions",
                "db_table": "barter_barter_transaction",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BarterCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Explanation of the counter offer"
                    ),
                ),
                (
                    "preferred_meeting_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("in_person", "In Person"),
                            ("mail", "Mail Exchange"),
                            ("pickup", "Pickup/Dropoff"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "proposed_meeting_location",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "proposed_meeting_time",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("is_accepted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "counter_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Barter Counter Offer",
                "verbose_name_plural": "Barter Counter Offers",
                "db_table": "barter_barter_counter",
                "ordering": ["-created_at"],
            },
        ),
    ]
