# Generated by Django 5.2.8 on 2025-11-27 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("barter", "0001_initial"),
        ("books", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bartercounter",
            name="offered_books",
            field=models.ManyToManyField(
                blank=True,
                related_name="counter_offered_books",
                to="books.bookcopy",
            ),
        ),
        migrations.AddField(
            model_name="bartercounter",
            name="requested_books",
            field=models.ManyToManyField(
                blank=True,
                related_name="counter_requested_books",
                to="books.bookcopy",
            ),
        ),
        migrations.AddField(
            model_name="barterrating",
            name="rated_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_ratings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="barterrating",
            name="rater",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="given_ratings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="barterrequest",
            name="offered_book",
            field=models.ForeignKey(
                blank=True,
                help_text="Book copy offered by the requester (final selection by recipient)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offered_in_barters",
                to="books.bookcopy",
            ),
        ),
        migrations.AddField(
            model_name="barterrequest",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_barter_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="barterrequest",
            name="requested_book",
            field=models.ForeignKey(
                blank=True,
                help_text="Book copy requested from the recipient",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requested_in_barters",
                to="books.bookcopy",
            ),
        ),
        migrations.AddField(
            model_name="barterrequest",
            name="requester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_barter_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bartercounter",
            name="original_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="counter_offers",
                to="barter.barterrequest",
            ),
        ),
        migrations.AddField(
            model_name="bartertransaction",
            name="barter_request",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaction",
                to="barter.barterrequest",
            ),
        ),
        migrations.AddField(
            model_name="barterrating",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="barter.bartertransaction",
            ),
        ),
        migrations.AddIndex(
            model_name="barterrequest",
            index=models.Index(
                fields=["requester"], name="barter_bart_request_087530_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="barterrequest",
            index=models.Index(
                fields=["recipient"], name="barter_bart_recipie_17de8f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="barterrequest",
            index=models.Index(
                fields=["status"], name="barter_bart_status_6cdc46_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="barterrequest",
            index=models.Index(
                fields=["created_at"], name="barter_bart_created_806a33_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="barterrating",
            unique_together={("transaction", "rater", "rated_user")},
        ),
    ]
