# Generated by Django 5.2.7 on 2025-11-01 16:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barter", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barterrequest",
            name="id",
            field=models.AutoField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
