# Generated by Django 5.2.7 on 2025-11-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barter", "0003_barterrequest_single_book_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barterrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("counter_proposed", "Counter Proposed"),
                    ("rejected", "Rejected"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
