# Generated by Django 5.2.8 on 2025-11-15 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("barter", "0003_alter_barterrequest_id"),
        ("barter", "0004_alter_barterrequest_status"),
    ]

    operations = []
