# Generated by Django 5.2.8 on 2025-11-16 03:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("barter", "0005_merge_20251115_1449"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barterrequest",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
