# Generated by Django 5.2.6 on 2025-09-27 07:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("barter_request", "Barter Request"),
                            ("barter_accepted", "Barter Accepted"),
                            ("barter_rejected", "Barter Rejected"),
                            ("barter_completed", "Barter Completed"),
                            ("message_received", "Message Received"),
                            ("post_liked", "Post Liked"),
                            ("comment_received", "Comment Received"),
                            ("user_followed", "User Followed"),
                            ("book_recommended", "Book Recommended"),
                            ("club_invitation", "Club Invitation"),
                            ("club_discussion", "Club Discussion"),
                            ("system_announcement", "System Announcement"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("title_template", models.CharField(max_length=200)),
                ("message_template", models.TextField()),
                (
                    "email_subject_template",
                    models.CharField(blank=True, max_length=200),
                ),
                ("email_body_template", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "default_priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Notification Template",
                "verbose_name_plural": "Notification Templates",
                "db_table": "notify_notification_template",
            },
        ),
        migrations.CreateModel(
            name="NotificationBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("target_all_users", models.BooleanField(default=False)),
                ("is_sent", models.BooleanField(default=False)),
                ("sent_count", models.IntegerField(default=0)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="targeted_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Batch",
                "verbose_name_plural": "Notification Batches",
                "db_table": "notify_notification_batch",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_barter_requests", models.BooleanField(default=True)),
                ("email_barter_updates", models.BooleanField(default=True)),
                ("email_messages", models.BooleanField(default=True)),
                ("email_social_activity", models.BooleanField(default=False)),
                ("email_recommendations", models.BooleanField(default=True)),
                ("email_club_activity", models.BooleanField(default=True)),
                ("email_system_announcements", models.BooleanField(default=True)),
                ("push_barter_requests", models.BooleanField(default=True)),
                ("push_barter_updates", models.BooleanField(default=True)),
                ("push_messages", models.BooleanField(default=True)),
                ("push_social_activity", models.BooleanField(default=True)),
                ("push_recommendations", models.BooleanField(default=True)),
                ("push_club_activity", models.BooleanField(default=True)),
                ("push_system_announcements", models.BooleanField(default=True)),
                ("inapp_barter_requests", models.BooleanField(default=True)),
                ("inapp_barter_updates", models.BooleanField(default=True)),
                ("inapp_messages", models.BooleanField(default=True)),
                ("inapp_social_activity", models.BooleanField(default=True)),
                ("inapp_recommendations", models.BooleanField(default=True)),
                ("inapp_club_activity", models.BooleanField(default=True)),
                ("inapp_system_announcements", models.BooleanField(default=True)),
                (
                    "digest_frequency",
                    models.CharField(
                        choices=[
                            ("never", "Never"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="weekly",
                        max_length=20,
                    ),
                ),
                ("quiet_hours_enabled", models.BooleanField(default=False)),
                ("quiet_hours_start", models.TimeField(blank=True, null=True)),
                ("quiet_hours_end", models.TimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Preference",
                "verbose_name_plural": "Notification Preferences",
                "db_table": "notify_notification_preference",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("barter_request", "Barter Request"),
                            ("barter_accepted", "Barter Accepted"),
                            ("barter_rejected", "Barter Rejected"),
                            ("barter_completed", "Barter Completed"),
                            ("message_received", "Message Received"),
                            ("post_liked", "Post Liked"),
                            ("comment_received", "Comment Received"),
                            ("user_followed", "User Followed"),
                            ("book_recommended", "Book Recommended"),
                            ("club_invitation", "Club Invitation"),
                            ("club_discussion", "Club Discussion"),
                            ("system_announcement", "System Announcement"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                ("object_id", models.CharField(blank=True, max_length=255, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("is_email_sent", models.BooleanField(default=False)),
                ("is_push_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "db_table": "notify_notification",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient"], name="notify_noti_recipie_22614d_idx"
                    ),
                    models.Index(
                        fields=["notification_type"],
                        name="notify_noti_notific_315064_idx",
                    ),
                    models.Index(
                        fields=["is_read"], name="notify_noti_is_read_eee8c9_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="notify_noti_created_aa2420_idx"
                    ),
                    models.Index(
                        fields=["priority"], name="notify_noti_priorit_dc1d6a_idx"
                    ),
                ],
            },
        ),
    ]
