# Generated by Django 5.2.7 on 2025-11-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notify", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("barter_request", "Barter Request"),
                    ("barter_accepted", "Barter Accepted"),
                    ("barter_rejected", "Barter Rejected"),
                    ("barter_completed", "Barter Completed"),
                    ("message_received", "Message Received"),
                    ("post_liked", "Post Liked"),
                    ("comment_received", "Comment Received"),
                    ("book_wishlisted", "Book Wishlisted"),
                    ("user_followed", "User Followed"),
                    ("book_recommended", "Book Recommended"),
                    ("club_invitation", "Club Invitation"),
                    ("club_discussion", "Club Discussion"),
                    ("system_announcement", "System Announcement"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="notificationtemplate",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("barter_request", "Barter Request"),
                    ("barter_accepted", "Barter Accepted"),
                    ("barter_rejected", "Barter Rejected"),
                    ("barter_completed", "Barter Completed"),
                    ("message_received", "Message Received"),
                    ("post_liked", "Post Liked"),
                    ("comment_received", "Comment Received"),
                    ("book_wishlisted", "Book Wishlisted"),
                    ("user_followed", "User Followed"),
                    ("book_recommended", "Book Recommended"),
                    ("club_invitation", "Club Invitation"),
                    ("club_discussion", "Club Discussion"),
                    ("system_announcement", "System Announcement"),
                ],
                max_length=30,
                unique=True,
            ),
        ),
    ]
