# Generated by Django 5.2.8 on 2025-11-27 14:26

import django.core.validators
import django.db.models.deletion
import taggit.managers
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("bio", models.TextField(blank=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("death_date", models.DateField(blank=True, null=True)),
                ("nationality", models.CharField(blank=True, max_length=50)),
                ("is_onboarding_choice", models.BooleanField(default=False, help_text="온보딩 설문 선택지에 포함할지 여부")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Author",
                "verbose_name_plural": "Authors",
                "db_table": "books_author",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_onboarding_choice", models.BooleanField(default=True, help_text="온보딩 설문 선택지에 포함할지 여부")),
            ],
            options={
                "verbose_name": "Genre",
                "verbose_name_plural": "Genres",
                "db_table": "books_genre",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("website", models.URLField(blank=True)),
                ("founded_year", models.IntegerField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Publisher",
                "verbose_name_plural": "Publishers",
                "db_table": "books_publisher",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Translator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("bio", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Translator",
                "verbose_name_plural": "Translators",
                "db_table": "books_translator",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BookPublication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=200)),
                (
                    "isbn_10",
                    models.CharField(
                        blank=True, max_length=10, null=True, unique=True
                    ),
                ),
                (
                    "isbn_13",
                    models.CharField(
                        blank=True, max_length=13, null=True, unique=True
                    ),
                ),
                ("publication_date", models.DateField(blank=True, null=True)),
                ("edition", models.CharField(blank=True, max_length=50)),
                (
                    "pages",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ],
                    ),
                ),
                (
                    "language",
                    models.CharField(default="English", max_length=30),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="book_covers/"
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to the book detail page on external API (e.g., Kakao)",
                        max_length=1024,
                    ),
                ),
                (
                    "original_price",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Original price from external API",
                        null=True,
                    ),
                ),
                (
                    "sale_price",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Sale price from external API",
                        null=True,
                    ),
                ),
                (
                    "sales_status",
                    models.CharField(
                        blank=True,
                        help_text="Sales status from external API (e.g., 정상, 품절, 절판)",
                        max_length=50,
                    ),
                ),
                (
                    "category_scores",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Cached LLM category scores (label + score dicts)",
                    ),
                ),
                (
                    "taste_profile",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Cached LLM taste profile (genres, moods, purposes, length)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "authors",
                    models.ManyToManyField(
                        related_name="publications", to="books.author"
                    ),
                ),
                (
                    "genres",
                    models.ManyToManyField(
                        blank=True,
                        related_name="publications",
                        to="books.genre",
                    ),
                ),
                (
                    "is_onboarding_choice",
                    models.BooleanField(
                        default=False, help_text="온보딩 설문 선택지에 포함할지 여부"
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="books.publisher",
                    ),
                ),
                (
                    "translators",
                    models.ManyToManyField(
                        blank=True,
                        related_name="publications",
                        to="books.translator",
                    ),
                ),
            ],
            options={
                "verbose_name": "Book Publication",
                "verbose_name_plural": "Book Publications",
                "db_table": "books_book_publication",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="BookCopy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("like_new", "Like New"),
                            ("very_good", "Very Good"),
                            ("good", "Good"),
                            ("acceptable", "Acceptable"),
                            ("poor", "Poor"),
                        ],
                        default="good",
                        max_length=20,
                    ),
                ),
                (
                    "owner_notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the book's condition or special features",
                    ),
                ),
                (
                    "trade_status",
                    models.CharField(
                        choices=[
                            ("available", "Available for Trade"),
                            ("pending", "Pending Trade"),
                            ("traded", "Traded"),
                            ("not_available", "Not Available"),
                        ],
                        db_column="availability",
                        default="available",
                        max_length=20,
                    ),
                ),
                (
                    "is_for_barter",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the owner wants to trade this book (user setting)",
                    ),
                ),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("review_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_copies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="copies",
                        to="books.bookpublication",
                    ),
                ),
                (
                    "preferred_genres_for_trade",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Genres you'd like to receive in exchange",
                        related_name="book_copies_wanted_for_trade",
                        to="books.genre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Book Copy",
                "verbose_name_plural": "Book Copies",
                "db_table": "books_book_copy",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BookReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "book_title",
                    models.CharField(
                        help_text="Title of the book being reviewed",
                        max_length=200,
                    ),
                ),
                (
                    "author_name",
                    models.CharField(
                        blank=True,
                        help_text="Author(s) of the book being reviewed",
                        max_length=200,
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        help_text="Rate the book from 1 to 5 stars",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100)),
                ("content", models.TextField()),
                (
                    "image_urls",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of image URLs for the review",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="books.bookcopy",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Book Review",
                "verbose_name_plural": "Book Reviews",
                "db_table": "books_book_review",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReadingStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("want_to_read", "Want to Read"),
                            ("currently_reading", "Currently Reading"),
                            ("read", "Read"),
                            ("did_not_finish", "Did Not Finish"),
                        ],
                        default="want_to_read",
                        max_length=20,
                    ),
                ),
                (
                    "pages_read",
                    models.IntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0)
                        ],
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("finish_date", models.DateField(blank=True, null=True)),
                (
                    "personal_rating",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Personal reading notes"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_statuses",
                        to="books.bookcopy",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_statuses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reading Status",
                "verbose_name_plural": "Reading Statuses",
                "db_table": "books_reading_status",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewHelpfulVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.bookreview",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Review Helpful Vote",
                "verbose_name_plural": "Review Helpful Votes",
                "db_table": "books_review_helpful_vote",
            },
        ),
        migrations.AddField(
            model_name="bookreview",
            name="helpful_votes",
            field=models.ManyToManyField(
                blank=True,
                related_name="helpful_reviews",
                through="books.ReviewHelpfulVote",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="BookCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Make this collection visible to others",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "books",
                    models.ManyToManyField(
                        blank=True,
                        related_name="collections",
                        to="books.bookcopy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Book Collection",
                "verbose_name_plural": "Book Collections",
                "db_table": "books_book_collection",
                "ordering": ["-updated_at"],
                "unique_together": {("owner", "name")},
            },
        ),
        migrations.CreateModel(
            name="BookWishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=1,
                        help_text="Priority level (1=Low, 5=High)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Personal notes about why you want this book",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlisted_by",
                        to="books.bookcopy",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Book Wishlist Item",
                "verbose_name_plural": "Book Wishlist Items",
                "db_table": "books_book_wishlist",
                "ordering": ["-priority", "-created_at"],
                "unique_together": {("user", "book")},
            },
        ),
        migrations.AddIndex(
            model_name="bookcopy",
            index=models.Index(
                fields=["owner"], name="books_book__owner_i_541bbc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookcopy",
            index=models.Index(
                fields=["trade_status"], name="books_book__availab_666cb4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookcopy",
            index=models.Index(
                fields=["is_for_barter"], name="books_book__is_for__8dc2e8_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="readingstatus",
            unique_together={("user", "book")},
        ),
        migrations.AlterUniqueTogether(
            name="reviewhelpfulvote",
            unique_together={("review", "user")},
        ),
        migrations.AddIndex(
            model_name="bookreview",
            index=models.Index(
                fields=["reviewer", "-created_at"],
                name="books_book__reviewe_e24b8d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bookreview",
            index=models.Index(
                fields=["book_title"], name="books_book__book_ti_c906f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookpublication",
            index=models.Index(
                fields=["title"], name="books_book__title_c931ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookpublication",
            index=models.Index(
                fields=["isbn_13"], name="books_book__isbn_13_c060a9_idx"
            ),
        ),
    ]
