# Generated by Django 5.2.7 on 2025-10-18 17:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="bookreview",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="bookreview",
            name="author_name",
            field=models.CharField(
                blank=True,
                help_text="Author(s) of the book being reviewed",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="bookreview",
            name="book_title",
            field=models.CharField(
                default="",
                help_text="Title of the book being reviewed",
                max_length=200,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bookreview",
            name="image_urls",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of image URLs for the review",
            ),
        ),
        migrations.AlterField(
            model_name="bookreview",
            name="book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="books.book",
            ),
        ),
        migrations.AlterField(
            model_name="bookreview",
            name="rating",
            field=models.IntegerField(
                blank=True,
                help_text="Rate the book from 1 to 5 stars",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="bookreview",
            index=models.Index(
                fields=["reviewer", "-created_at"],
                name="books_book__reviewe_e24b8d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bookreview",
            index=models.Index(
                fields=["book_title"], name="books_book__book_ti_c906f0_idx"
            ),
        ),
    ]
