# Generated by Django 5.2.7 on 2025-11-06 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_alter_bookreview_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookreview",
            name="isbn",
            field=models.CharField(
                blank=True,
                help_text="ISBN of the book being reviewed",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="bookreview",
            name="publisher",
            field=models.CharField(
                blank=True,
                help_text="Publisher of the book being reviewed",
                max_length=200,
            ),
        ),
    ]
