# Generated by Django 5.2.7 on 2025-11-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_alter_bookreview_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Translator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("bio", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Translator",
                "verbose_name_plural": "Translators",
                "db_table": "books_translator",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="book",
            name="external_url",
            field=models.URLField(
                blank=True,
                help_text="URL to the book detail page on external API (e.g., Kakao)",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="original_price",
            field=models.IntegerField(
                blank=True,
                help_text="Original price from external API",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="sale_price",
            field=models.IntegerField(
                blank=True, help_text="Sale price from external API", null=True
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="sales_status",
            field=models.CharField(
                blank=True,
                help_text="Sales status from external API (e.g., 정상, 품절, 절판)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="translators",
            field=models.ManyToManyField(
                blank=True, related_name="books", to="books.translator"
            ),
        ),
    ]
