# Generated by Django 5.2.7 on 2025-11-11 10:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_bookreview_isbn_bookreview_publisher"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="book",
            name="books_book_availab_7c5efd_idx",
        ),
        migrations.RemoveField(
            model_name="book",
            name="availability",
        ),
        migrations.RemoveField(
            model_name="bookreview",
            name="isbn",
        ),
        migrations.RemoveField(
            model_name="bookreview",
            name="publisher",
        ),
        migrations.AddField(
            model_name="book",
            name="trade_status",
            field=models.CharField(
                choices=[
                    ("available", "Available for Trade"),
                    ("pending", "Pending Trade"),
                    ("traded", "Traded"),
                    ("not_available", "Not Available"),
                ],
                default="available",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="is_for_barter",
            field=models.BooleanField(
                default=True,
                help_text="Whether the owner wants to trade this book (user setting)",
            ),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(
                fields=["trade_status"], name="books_book_trade_s_b469ad_idx"
            ),
        ),
    ]
