# Generated by Django 5.2.7 on 2025-11-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "books",
            "0003_translator_book_external_url_book_original_price_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="original_price",
            field=models.BigIntegerField(
                blank=True,
                help_text="Original price from external API",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="sale_price",
            field=models.BigIntegerField(
                blank=True, help_text="Sale price from external API", null=True
            ),
        ),
    ]
