# Generated by Django 5.2.7 on 2025-11-05 17:45

import django.core.validators
import django.db.models.deletion
import taggit.managers
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_alter_book_original_price_alter_book_sale_price"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BookCopy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("like_new", "Like New"),
                            ("very_good", "Very Good"),
                            ("good", "Good"),
                            ("acceptable", "Acceptable"),
                            ("poor", "Poor"),
                        ],
                        default="good",
                        max_length=20,
                    ),
                ),
                (
                    "availability",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("pending", "Pending Trade"),
                            ("traded", "Traded"),
                            ("not_available", "Not Available"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                (
                    "owner_notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the book's condition or special features",
                    ),
                ),
                ("is_for_barter", models.BooleanField(default=True)),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("review_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_copies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "preferred_genres_for_trade",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Genres you'd like to receive in exchange",
                        related_name="book_copies_wanted_for_trade",
                        to="books.genre",
                    ),
                ),
                (
                    "tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "Book Copy",
                "verbose_name_plural": "Book Copies",
                "db_table": "books_book_copy",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="bookcollection",
            name="books",
            field=models.ManyToManyField(
                blank=True, related_name="collections", to="books.bookcopy"
            ),
        ),
        migrations.AlterField(
            model_name="bookreview",
            name="book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="books.bookcopy",
            ),
        ),
        migrations.AlterField(
            model_name="bookwishlist",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wishlisted_by",
                to="books.bookcopy",
            ),
        ),
        migrations.AlterField(
            model_name="readingstatus",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reading_statuses",
                to="books.bookcopy",
            ),
        ),
        migrations.CreateModel(
            name="BookPublication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=200)),
                (
                    "isbn_10",
                    models.CharField(
                        blank=True, max_length=10, null=True, unique=True
                    ),
                ),
                (
                    "isbn_13",
                    models.CharField(
                        blank=True, max_length=13, null=True, unique=True
                    ),
                ),
                ("publication_date", models.DateField(blank=True, null=True)),
                ("edition", models.CharField(blank=True, max_length=50)),
                (
                    "pages",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ],
                    ),
                ),
                (
                    "language",
                    models.CharField(default="English", max_length=30),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="book_covers/"
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to the book detail page on external API (e.g., Kakao)",
                    ),
                ),
                (
                    "original_price",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Original price from external API",
                        null=True,
                    ),
                ),
                (
                    "sale_price",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Sale price from external API",
                        null=True,
                    ),
                ),
                (
                    "sales_status",
                    models.CharField(
                        blank=True,
                        help_text="Sales status from external API (e.g., 정상, 품절, 절판)",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "authors",
                    models.ManyToManyField(
                        related_name="publications", to="books.author"
                    ),
                ),
                (
                    "genres",
                    models.ManyToManyField(
                        blank=True,
                        related_name="publications",
                        to="books.genre",
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="books.publisher",
                    ),
                ),
                (
                    "translators",
                    models.ManyToManyField(
                        blank=True,
                        related_name="publications",
                        to="books.translator",
                    ),
                ),
            ],
            options={
                "verbose_name": "Book Publication",
                "verbose_name_plural": "Book Publications",
                "db_table": "books_book_publication",
                "ordering": ["title"],
            },
        ),
        migrations.AddField(
            model_name="bookcopy",
            name="publication",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="copies",
                to="books.bookpublication",
            ),
        ),
    ]
