# Generated by Django 5.2.8 on 2025-11-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_remove_book_books_book_isbn_13_a77f18_idx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="authors",
        ),
        migrations.AddField(
            model_name="book",
            name="authors",
            field=models.CharField(default="", max_length=255),
        ),
    ]
