# Generated by Django 5.2.7 on 2025-11-05 17:45

from django.db import migrations, models


def migrate_book_data(apps, schema_editor):
    Book = apps.get_model("books", "Book")
    BookCopy = apps.get_model("books", "BookCopy")
    BookPublication = apps.get_model("books", "BookPublication")
    TaggedItem = apps.get_model("taggit", "TaggedItem")
    ContentType = apps.get_model("contenttypes", "ContentType")

    publication_cache = {}

    def get_or_create_publication(book):
        key = None
        if book.isbn_13:
            key = ("isbn13", book.isbn_13)
        elif book.isbn_10:
            key = ("isbn10", book.isbn_10)
        else:
            key = (
                "meta",
                book.title or "",
                book.subtitle or "",
                book.publisher_id,
            )

        if key in publication_cache:
            return publication_cache[key]

        publication = None
        if book.isbn_13:
            publication = BookPublication.objects.filter(
                isbn_13=book.isbn_13
            ).first()
        if publication is None and book.isbn_10:
            publication = BookPublication.objects.filter(
                isbn_10=book.isbn_10
            ).first()
        if publication is None:
            publication = BookPublication.objects.filter(
                title=book.title or "",
                subtitle=book.subtitle or "",
                publisher_id=book.publisher_id,
            ).first()

        if publication is None:
            publication = BookPublication.objects.create(
                title=book.title or "Untitled Book",
                subtitle=book.subtitle or "",
                isbn_13=book.isbn_13,
                isbn_10=book.isbn_10,
                publication_date=book.publication_date,
                edition=book.edition,
                pages=book.pages,
                language=book.language,
                description=book.description,
                cover_image=book.cover_image,
                external_url=book.external_url,
                original_price=book.original_price,
                sale_price=book.sale_price,
                sales_status=book.sales_status,
                publisher_id=book.publisher_id,
            )
            publication.authors.set(book.authors.all())
            publication.translators.set(book.translators.all())
            publication.genres.set(book.genres.all())

        publication_cache[key] = publication
        return publication

    for book in Book.objects.all():
        if BookCopy.objects.filter(pk=book.pk).exists():
            continue

        publication = get_or_create_publication(book)

        copy = BookCopy.objects.create(
            id=book.id,
            publication=publication,
            owner_id=book.owner_id,
            condition=book.condition,
            availability=book.availability,
            owner_notes=book.owner_notes,
            is_for_barter=book.is_for_barter,
            average_rating=book.average_rating,
            review_count=book.review_count,
            created_at=book.created_at,
            updated_at=book.updated_at,
        )

        copy.preferred_genres_for_trade.set(
            book.preferred_genres_for_trade.all()
        )

    try:
        old_ct = ContentType.objects.get(app_label="books", model="book")
        new_ct = ContentType.objects.get(
            app_label="books", model="bookcopy"
        )
        TaggedItem.objects.filter(content_type=old_ct).update(
            content_type=new_ct
        )
    except ContentType.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("barter", "0003_alter_bartercounter_offered_books_and_more"),
        ("books", "0005_remove_book_authors_remove_book_genres_and_more"),
        ("social", "0003_alter_bookclub_current_book_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_book_data, migrations.RunPython.noop),
        migrations.DeleteModel(
            name="Book",
        ),
        migrations.AddIndex(
            model_name="bookpublication",
            index=models.Index(
                fields=["title"], name="books_book__title_c931ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookpublication",
            index=models.Index(
                fields=["isbn_13"], name="books_book__isbn_13_c060a9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookcopy",
            index=models.Index(
                fields=["owner"], name="books_book__owner_i_541bbc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookcopy",
            index=models.Index(
                fields=["availability"], name="books_book__availab_666cb4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookcopy",
            index=models.Index(
                fields=["is_for_barter"], name="books_book__is_for__8dc2e8_idx"
            ),
        ),
    ]
