# Generated by Django 5.2.8 on 2025-11-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0006_remove_book_authors_book_authors"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="authors",
        ),
        migrations.AddField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(
                related_name="books", to="books.author"
            ),
        ),
    ]
