# Generated by Django 5.2.8 on 2025-11-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="author_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="post",
            name="book_cover_image",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="post",
            name="book_title",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
