# Generated by Django 6.0 on 2025-12-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="book_title",
            field=models.CharField(
                blank=True,
                help_text="Title of the book for review posts",
                max_length=200,
            ),
        ),
    ]
