# Generated by Django 5.2.7 on 2025-10-23 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        # Migration removed: changing Post.id to AutoField would coerce existing
        # UUID values to integers which is unsafe and not desired.
        # This migration intentionally contains no operations to act as a no-op
        # placeholder. If this file should be removed entirely, do so once all
        # references and CI pipelines are updated.
    ]
