# Generated by Django 5.2.7 on 2025-11-04 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_post_id'),
        ('books', '0002_alter_bookreview_unique_together_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Drop and recreate Post table with new ID type
        migrations.RunSQL(
            sql='''
                -- Drop dependent tables first
                DROP TABLE IF EXISTS social_postlike CASCADE;
                DROP TABLE IF EXISTS social_comment CASCADE;
                DROP TABLE IF EXISTS social_post CASCADE;
            ''',
            reverse_sql=migrations.RunSQL.noop,
        ),
        
        # Recreate Post table with integer ID
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post_type', models.CharField(
                    choices=[
                        ('text', 'Text Post'),
                        ('book_review', 'Book Review'),
                        ('barter_offer', 'Barter Offer'),
                    ],
                    max_length=20
                )),
                ('content', models.TextField()),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='posts',
                    to=settings.AUTH_USER_MODEL
                )),
                ('related_book', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='posts',
                    to='books.book'
                )),
            ],
            options={
                'db_table': 'social_post',
                'ordering': ['-created_at'],
            },
        ),
        
        # Recreate PostLike table
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='likes',
                    to='social.post'
                )),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='liked_posts',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'db_table': 'social_postlike',
                'unique_together': {('user', 'post')},
            },
        ),
        
        # Recreate Comment table
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='comments',
                    to=settings.AUTH_USER_MODEL
                )),
                ('post', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='comments',
                    to='social.post'
                )),
            ],
            options={
                'db_table': 'social_comment',
                'ordering': ['created_at'],
            },
        ),
    ]
