# Generated by Django 5.2.7 on 2025-11-05 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_remove_book_authors_remove_book_genres_and_more"),
        ("social", "0002_alter_post_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookclub",
            name="current_book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_in_clubs",
                to="books.bookcopy",
            ),
        ),
        migrations.AlterField(
            model_name="bookclubdiscussion",
            name="related_book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="club_discussions",
                to="books.bookcopy",
            ),
        ),
        migrations.AlterField(
            model_name="directmessage",
            name="related_book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_messages",
                to="books.bookcopy",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="related_book",
            field=models.ForeignKey(
                blank=True,
                help_text="Book this post is about (optional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_posts",
                to="books.bookcopy",
            ),
        ),
        migrations.AlterField(
            model_name="recommendation",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recommendations",
                to="books.bookcopy",
            ),
        ),
        migrations.AlterField(
            model_name="useractivity",
            name="related_book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="books.bookcopy",
            ),
        ),
    ]
