# Generated by Django 6.0 on 2025-12-08
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0002_post_book_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="author_name",
            field=models.CharField(max_length=200, blank=True, default=""),
        ),
    ]
