# Generated by Django 5.2.7 on 2025-11-11 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0003_alter_post_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="post",
            name="social_post_author_idx",
        ),
        migrations.RemoveIndex(
            model_name="post",
            name="social_post_type_idx",
        ),
        migrations.RemoveIndex(
            model_name="post",
            name="social_post_created_idx",
        ),
        migrations.RemoveIndex(
            model_name="post",
            name="social_post_public_idx",
        ),
        migrations.AddField(
            model_name="comment",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                related_name="liked_comments",
                through="social.CommentLike",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="post_type",
            field=models.CharField(
                choices=[
                    ("text", "Text Post"),
                    ("book_review", "Book Review"),
                    ("book_recommendation", "Book Recommendation"),
                    ("reading_update", "Reading Update"),
                    ("barter_success", "Successful Barter"),
                ],
                default="text",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="postlike",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_post_likes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
