# Generated by Django 5.2.7 on 2025-12-09 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0003_post_author_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="book_cover_image",
        ),
    ]
